package br.edu.ifms.requerimentos.model;

public enum DescricaoTipoRequerimento {
	CANCELAMENTO_MATRICULA,
	CANCELAMENTO_UNIDADE_CURRICULAR,
	CERTIFICADO_DE_QUALIFICACAO_PROFISSIONAL,
	CONVALIDACAO,
	DECLARACAO,
	DESISTENCIA_DE_CURSO,
	ENREQUECIMENTO_PROFISSIONAL,
	EXAME_DE_SUFICIENCIA,
	HISTORICO_ESCOLAR,
	MATRICULA_EM_UNIDADE_CURRICULAR,
	MUDANCA_DE_TURMA,
	MUDANCA_DE_TURNO,
	TRANCAMENTO,
	TRANSFERENCIA,
	SEGUNDA_CHAMADA,
	OUTROS
}
