/*
 * Java bean class for entity table anexo 
 * Created on 6 jul 2016 ( Date ISO 2016-07-06 - Time 16:42:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package model;

import javax.persistence.Column;
import javax.persistence.Id;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;

public class Anexo {
	@Id
	@Column(name = "anexo_id")
	private Integer id;
	@Column(name = "nome_original")
	private String nome;
	private String hash;
	@ManyToOne
	private Requerimento requerimento;
	@OneToMany
	private Integer servidor;
	@Column(name = "nome_original")
	private String data;
	private Boolean sigiloso;
	
	public Integer getId() {
		return id;
	}
	public void setId(Integer id) {
		this.id = id;
	}
	public String getNome() {
		return nome;
	}
	public void setNome(String nome) {
		this.nome = nome;
	}
	public String getHash() {
		return hash;
	}
	public void setHash(String hash) {
		this.hash = hash;
	}
	public Requerimento getRequerimento() {
		return requerimento;
	}
	public void setRequerimento(Requerimento requerimento) {
		this.requerimento = requerimento;
	}
	public Integer getServidor() {
		return servidor;
	}
	public void setServidor(Integer servidor) {
		this.servidor = servidor;
	}
	public String getData() {
		return data;
	}
	public void setData(String data) {
		this.data = data;
	}
	public Boolean getSigiloso() {
		return sigiloso;
	}
	public void setSigiloso(Boolean sigiloso) {
		this.sigiloso = sigiloso;
	}

}
