/*
 * Java bean class for entity table dadoscerel 
 * Created on 6 jul 2016 ( Date ISO 2016-07-06 - Time 16:42:20 )
 * Generated by Telosys Tools Generator ( version 2.1.1 )
 */

package model;

import java.io.Serializable;


/**
 * Entity bean for table "dadoscerel"
 * 
 * @author Telosys Tools Generator
 *
 */
public class Dadoscerel implements Serializable
{
    private static final long serialVersionUID = 1L;


    private String     ra           ;
    private String     nome         ;
    private String     email        ;
    private String     nomeMae      ;
    private String     telefone     ;
    private String     celular      ;
    private String     cpf          ;
    private String     matricula    ;
    private String     curso        ;

    /**
     * Default constructor
     */
    public Dadoscerel()
    {
        super();
    }
    
    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR THE PRIMARY KEY 
    //----------------------------------------------------------------------

    //----------------------------------------------------------------------
    // GETTER(S) & SETTER(S) FOR DATA FIELDS
    //----------------------------------------------------------------------
    //--- DATABASE MAPPING : ra ( text ) 
    /**
     * Set the "ra" field value
     * This field is mapped on the database column "ra" ( type "text", NotNull : false ) 
     * @param ra
     */
    public void setRa( String ra )
    {
        this.ra = ra;
    }
    /**
     * Get the "ra" field value
     * This field is mapped on the database column "ra" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getRa()
    {
        return this.ra;
    }

    //--- DATABASE MAPPING : nome ( text ) 
    /**
     * Set the "nome" field value
     * This field is mapped on the database column "nome" ( type "text", NotNull : false ) 
     * @param nome
     */
    public void setNome( String nome )
    {
        this.nome = nome;
    }
    /**
     * Get the "nome" field value
     * This field is mapped on the database column "nome" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getNome()
    {
        return this.nome;
    }

    //--- DATABASE MAPPING : email ( text ) 
    /**
     * Set the "email" field value
     * This field is mapped on the database column "email" ( type "text", NotNull : false ) 
     * @param email
     */
    public void setEmail( String email )
    {
        this.email = email;
    }
    /**
     * Get the "email" field value
     * This field is mapped on the database column "email" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getEmail()
    {
        return this.email;
    }

    //--- DATABASE MAPPING : nome_mae ( text ) 
    /**
     * Set the "nomeMae" field value
     * This field is mapped on the database column "nome_mae" ( type "text", NotNull : false ) 
     * @param nomeMae
     */
    public void setNomeMae( String nomeMae )
    {
        this.nomeMae = nomeMae;
    }
    /**
     * Get the "nomeMae" field value
     * This field is mapped on the database column "nome_mae" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getNomeMae()
    {
        return this.nomeMae;
    }

    //--- DATABASE MAPPING : telefone ( text ) 
    /**
     * Set the "telefone" field value
     * This field is mapped on the database column "telefone" ( type "text", NotNull : false ) 
     * @param telefone
     */
    public void setTelefone( String telefone )
    {
        this.telefone = telefone;
    }
    /**
     * Get the "telefone" field value
     * This field is mapped on the database column "telefone" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getTelefone()
    {
        return this.telefone;
    }

    //--- DATABASE MAPPING : celular ( text ) 
    /**
     * Set the "celular" field value
     * This field is mapped on the database column "celular" ( type "text", NotNull : false ) 
     * @param celular
     */
    public void setCelular( String celular )
    {
        this.celular = celular;
    }
    /**
     * Get the "celular" field value
     * This field is mapped on the database column "celular" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getCelular()
    {
        return this.celular;
    }

    //--- DATABASE MAPPING : cpf ( text ) 
    /**
     * Set the "cpf" field value
     * This field is mapped on the database column "cpf" ( type "text", NotNull : false ) 
     * @param cpf
     */
    public void setCpf( String cpf )
    {
        this.cpf = cpf;
    }
    /**
     * Get the "cpf" field value
     * This field is mapped on the database column "cpf" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getCpf()
    {
        return this.cpf;
    }

    //--- DATABASE MAPPING : matricula ( text ) 
    /**
     * Set the "matricula" field value
     * This field is mapped on the database column "matricula" ( type "text", NotNull : false ) 
     * @param matricula
     */
    public void setMatricula( String matricula )
    {
        this.matricula = matricula;
    }
    /**
     * Get the "matricula" field value
     * This field is mapped on the database column "matricula" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getMatricula()
    {
        return this.matricula;
    }

    //--- DATABASE MAPPING : curso ( text ) 
    /**
     * Set the "curso" field value
     * This field is mapped on the database column "curso" ( type "text", NotNull : false ) 
     * @param curso
     */
    public void setCurso( String curso )
    {
        this.curso = curso;
    }
    /**
     * Get the "curso" field value
     * This field is mapped on the database column "curso" ( type "text", NotNull : false ) 
     * @return the field value
     */
    public String getCurso()
    {
        return this.curso;
    }


    //----------------------------------------------------------------------
    // toString METHOD
    //----------------------------------------------------------------------
    public String toString() { 
        StringBuffer sb = new StringBuffer(); 
        sb.append(ra);
        sb.append("|");
        sb.append(nome);
        sb.append("|");
        sb.append(email);
        sb.append("|");
        sb.append(nomeMae);
        sb.append("|");
        sb.append(telefone);
        sb.append("|");
        sb.append(celular);
        sb.append("|");
        sb.append(cpf);
        sb.append("|");
        sb.append(matricula);
        sb.append("|");
        sb.append(curso);
        return sb.toString(); 
    } 


}
